(() => {
  'use strict';
  const KEY='aube-mobile-v1',app=document.querySelector('#app'),toast=document.querySelector('#toast');
  const defaults={profile:{name:'',level:''},tasks:[],exams:[],grades:[],focusSessions:[]};
  const load=()=>{try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}};
  const save=state=>localStorage.setItem(KEY,JSON.stringify(state));
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const iso=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  const today=()=>iso(new Date());
  const notify=message=>{toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)};
  const average=grades=>{const weight=grades.reduce((s,g)=>s+Number(g.coefficient||1),0);return weight?grades.reduce((s,g)=>s+(Number(g.score)/Math.max(1,Number(g.outOf||20))*20)*Number(g.coefficient||1),0)/weight:null};
  let view='home',timer=null;
  function navigate(next){view=next;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===next));render()}
  function render(){({home:renderHome,tasks:renderTasks,exams:renderExams,notes:renderNotes,settings:renderSettings}[view]||renderHome)()}
  function renderHome(){const s=load(),name=s.profile?.name||'toi',open=s.tasks.filter(t=>!t.done),nextExam=s.exams.filter(e=>e.date>=today()).sort((a,b)=>a.date.localeCompare(b.date))[0],focus=s.focusSessions.filter(x=>String(x.endedAt||'').startsWith(today())).reduce((n,x)=>n+Number(x.minutes||0),0);app.innerHTML=`<h1>Bonjour, ${esc(name)}.</h1><p>Ton organisation reste privée sur cet appareil.</p><div class="metrics"><div class="metric"><b>${open.length}</b><small>tâches ouvertes</small></div><div class="metric"><b>${s.exams.length}</b><small>examens</small></div><div class="metric"><b>${average(s.grades)===null?'—':average(s.grades).toFixed(1)}</b><small>moyenne /20</small></div><div class="metric"><b>${focus}</b><small>minutes aujourd’hui</small></div></div>${nextExam?`<section class="card"><small>Prochain examen</small><h2>${esc(nextExam.subject)} · ${esc(nextExam.title)}</h2><p>${esc(nextExam.date)} · ${nextExam.chapters.filter(c=>c.done).length}/${nextExam.chapters.length} chapitres</p><div class="progress"><i style="width:${nextExam.chapters.length?nextExam.chapters.filter(c=>c.done).length/nextExam.chapters.length*100:0}%"></i></div></section>`:''}<section class="card"><div class="toolbar"><div><small>Concentration</small><h2>Une chose à la fois</h2></div><button class="action primary" id="focusStart">Commencer</button></div></section><section class="card"><h2>À faire maintenant</h2>${open.slice(0,4).map(t=>`<div class="row"><input class="check" type="checkbox" data-home-task="${esc(t.id)}"><div><b>${esc(t.title)}</b><small>${esc(t.subject||'Personnel')} · ${esc(t.dueDate)}</small></div></div>`).join('')||'<div class="empty">Rien à faire pour le moment.</div>'}</section>`;app.querySelector('#focusStart').onclick=renderFocus;app.querySelectorAll('[data-home-task]').forEach(box=>box.onchange=()=>toggleTask(box.dataset.homeTask,true))}
  function renderFocus(){let remaining=25*60,started=Date.now();app.innerHTML='<section class="card focus"><small>Séance de concentration</small><time id="focusTime">25:00</time><p>Le téléphone reste calme. Une seule chose à la fois.</p><button class="danger" id="focusStop">Terminer</button></section>';const draw=()=>{const target=app.querySelector('#focusTime');if(!target)return;const m=Math.floor(remaining/60),sec=remaining%60;target.textContent=`${m}:${String(sec).padStart(2,'0')}`};const finish=()=>{clearInterval(timer);timer=null;const minutes=Math.max(1,Math.round((Date.now()-started)/60000)),s=load();s.focusSessions.push({id:crypto.randomUUID(),minutes,endedAt:new Date().toISOString()});save(s);notify(`${minutes} min enregistrée${minutes>1?'s':''}`);navigate('home')};draw();timer=setInterval(()=>{remaining--;draw();if(remaining<=0)finish()},1000);app.querySelector('#focusStop').onclick=finish}
  function renderTasks(){const s=load();app.innerHTML=`<h1>Mes tâches.</h1><p>Une liste simple, disponible même hors ligne.</p><section class="card"><form class="form inline" id="taskForm"><input class="field" name="title" required placeholder="Nom de la tâche"><input class="field" name="subject" placeholder="Matière"><input class="field" name="dueDate" type="date" min="${today()}" required><button class="action primary">Ajouter</button></form></section><section class="card">${s.tasks.map(t=>`<div class="row"><input class="check" type="checkbox" data-task="${esc(t.id)}" ${t.done?'checked':''}><div><b>${esc(t.title)}</b><small>${esc(t.subject||'Personnel')} · ${esc(t.dueDate)}</small></div><button class="danger" data-del-task="${esc(t.id)}">×</button></div>`).join('')||'<div class="empty">Aucune tâche.</div>'}</section>`;app.querySelector('#taskForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),s=load();s.tasks.unshift({id:crypto.randomUUID(),title:String(f.get('title')).trim(),subject:String(f.get('subject')).trim()||'Personnel',dueDate:String(f.get('dueDate')),done:false});save(s);renderTasks()};app.querySelectorAll('[data-task]').forEach(b=>b.onchange=()=>toggleTask(b.dataset.task,b.checked));app.querySelectorAll('[data-del-task]').forEach(b=>b.onclick=()=>{const s=load();s.tasks=s.tasks.filter(t=>t.id!==b.dataset.delTask);save(s);renderTasks()})}
  function toggleTask(id,done){const s=load();s.tasks=s.tasks.map(t=>t.id===id?{...t,done,completedAt:done?new Date().toISOString():null}:t);save(s);render()}
  function renderExams(){const s=load();app.innerHTML=`<h1>Mes examens.</h1><p>Les chapitres sont ceux que tu saisis.</p><section class="card"><form class="form" id="examForm"><input class="field" name="title" required placeholder="Nom de l’examen"><input class="field" name="subject" required placeholder="Matière"><input class="field" name="date" type="date" min="${today()}" required><textarea class="field" name="chapters" required placeholder="Un chapitre par ligne"></textarea><button class="action primary">Ajouter</button></form></section>${s.exams.map(exam=>`<section class="card"><div class="toolbar"><div><small>${esc(exam.subject)} · ${esc(exam.date)}</small><h2>${esc(exam.title)}</h2></div><button class="danger" data-del-exam="${esc(exam.id)}">Supprimer</button></div><div class="progress"><i style="width:${exam.chapters.length?exam.chapters.filter(c=>c.done).length/exam.chapters.length*100:0}%"></i></div>${exam.chapters.map(c=>`<div class="row"><input class="check" type="checkbox" data-exam="${esc(exam.id)}" data-chapter="${esc(c.id)}" ${c.done?'checked':''}><div><b>${esc(c.name)}</b></div></div>`).join('')}</section>`).join('')}`;app.querySelector('#examForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),s=load();s.exams.push({id:crypto.randomUUID(),title:String(f.get('title')).trim(),subject:String(f.get('subject')).trim(),date:String(f.get('date')),chapters:String(f.get('chapters')).split(/\r?\n/).map(name=>name.trim()).filter(Boolean).map(name=>({id:crypto.randomUUID(),name,done:false}))});save(s);renderExams()};app.querySelectorAll('[data-exam]').forEach(b=>b.onchange=()=>{const s=load(),exam=s.exams.find(e=>e.id===b.dataset.exam),chapter=exam?.chapters.find(c=>c.id===b.dataset.chapter);if(chapter)chapter.done=b.checked;save(s);renderExams()});app.querySelectorAll('[data-del-exam]').forEach(b=>b.onclick=()=>{const s=load();s.exams=s.exams.filter(e=>e.id!==b.dataset.delExam);save(s);renderExams()})}
  function renderNotes(){const s=load();app.innerHTML=`<h1>Mes notes.</h1><p>Moyenne pondérée : <b>${average(s.grades)===null?'—':average(s.grades).toFixed(1)}/20</b></p><section class="card"><form class="form" id="gradeForm"><input class="field" name="title" required placeholder="Contrôle ou devoir"><input class="field" name="subject" required placeholder="Matière"><input class="field" name="score" type="number" min="0" step=".25" required placeholder="Note"><input class="field" name="outOf" type="number" min="1" step=".25" value="20" required><input class="field" name="coefficient" type="number" min=".25" step=".25" value="1" required><button class="action primary">Ajouter</button></form></section><section class="card">${s.grades.map(g=>`<div class="row"><div><b>${esc(g.subject)} · ${esc(g.title)}</b><small>coefficient ${esc(g.coefficient)}</small></div><b>${esc(g.score)}/${esc(g.outOf)}</b><button class="danger" data-del-grade="${esc(g.id)}">×</button></div>`).join('')||'<div class="empty">Aucune note.</div>'}</section>`;app.querySelector('#gradeForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)),s=load();s.grades.unshift({id:crypto.randomUUID(),...v,date:today()});save(s);renderNotes()};app.querySelectorAll('[data-del-grade]').forEach(b=>b.onclick=()=>{const s=load();s.grades=s.grades.filter(g=>g.id!==b.dataset.delGrade);save(s);renderNotes()})}
  function renderSettings(){const s=load();app.innerHTML=`<h1>Mon Aube.</h1><p>Ce profil et ses données restent sur ce téléphone.</p><section class="card"><form class="form" id="profileForm"><label>Prénom<input class="field" name="name" value="${esc(s.profile?.name||'')}" required></label><label>Niveau scolaire<input class="field" name="level" value="${esc(s.profile?.level||'')}" placeholder="Ex. Terminale"></label><button class="action primary">Enregistrer</button></form></section><section class="card"><h2>Sauvegarde locale</h2><p>Exporte un fichier pour conserver ou déplacer tes données.</p><div class="toolbar"><button class="action" id="exportData">Exporter</button><label class="action">Importer<input id="importData" type="file" accept="application/json" hidden></label></div></section><section class="card"><h2>Installation</h2><p>Dans le navigateur, utilise « Ajouter à l’écran d’accueil ». Aube fonctionnera ensuite hors ligne.</p></section>`;app.querySelector('#profileForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),s=load();s.profile={name:String(f.get('name')).trim(),level:String(f.get('level')).trim()};save(s);notify('Profil enregistré')};app.querySelector('#exportData').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(load(),null,2)],{type:'application/json'}));a.download='aube-mobile-sauvegarde.json';a.click();URL.revokeObjectURL(a.href)};app.querySelector('#importData').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);save({...defaults,...parsed});notify('Sauvegarde restaurée');renderSettings()}catch{notify('Fichier invalide')}};reader.readAsText(file)}}
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
  let installPrompt=null;const installButton=document.querySelector('#installButton');window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;installButton.hidden=false});installButton.onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;installButton.hidden=true};
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));
  render();
})();
